---
- name: Deploy CI/CD Application
  hosts: webserver
  become: true

  tasks:

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull application Docker image
      community.docker.docker_image:
        name: your-dockerhub-username/automated-cicd-pipeline:latest
        source: pull

    - name: Run application container
      community.docker.docker_container:
        name: automated-cicd-pipeline
        image: your-dockerhub-username/automated-cicd-pipeline:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
